# Generated by Django 3.0 on 2021-12-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_rider',
        ),
    ]
